# Generated by Django 2.2.3 on 2019-07-30 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=150)),
                ('nominal', models.CharField(max_length=150)),
                ('quality', models.CharField(max_length=50)),
                ('probe', models.CharField(max_length=50)),
                ('original_equipment', models.CharField(max_length=255)),
                ('pure_metal', models.CharField(max_length=255)),
                ('mass', models.CharField(max_length=50)),
                ('diameter', models.CharField(max_length=50)),
                ('thickness', models.CharField(max_length=50)),
                ('copies', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinCatalog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ImgCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=255)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinCatalog.Coin')),
            ],
        ),
    ]
