# Generated by Django 2.2.3 on 2019-07-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinCatalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='copies',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='diameter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='manufacturer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='mass',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='nominal',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='original_equipment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='probe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='pure_metal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='quality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='short_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='thickness',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
