# Generated by Django 2.2.4 on 2019-08-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinCatalog', '0003_category_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogUser',
            fields=[
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('time_enrolled', models.DateTimeField(null=True)),
                ('photo', models.BinaryField(null=True)),
                ('vector', models.BinaryField(null=True)),
            ],
        ),
    ]
