# Generated by Django 2.2.4 on 2019-08-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinCatalog', '0005_coin_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lang',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
