# Generated by Django 2.2.4 on 2019-08-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinCatalog', '0007_auto_20190828_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='lang',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
