# Generated by Django 2.2.4 on 2019-08-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinCatalog', '0008_coin_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='en_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ru_name',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_copies',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_description',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_diameter',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_manufacturer',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_mass',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_name',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_nominal',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_notes',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_original_equipment',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_probe',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_pure_metal',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_quality',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_short_name',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='en_thickness',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_copies',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_description',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_diameter',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_manufacturer',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_mass',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_name',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_nominal',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_notes',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_original_equipment',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_probe',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_pure_metal',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_quality',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_short_name',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='ru_thickness',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='copies',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='diameter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='manufacturer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='mass',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='nominal',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='original_equipment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='probe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='pure_metal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='quality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='short_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='thickness',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
