# Generated by Django 2.2.4 on 2019-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinCatalog', '0009_auto_20190828_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lang',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
