# Generated by Django 2.2.4 on 2019-08-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinCatalog', '0010_category_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoguser',
            name='organization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dialoguser',
            name='photo_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dialoguser',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dialoguser',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
