# Generated by Django 2.2.4 on 2019-08-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinCatalog', '0011_auto_20190830_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
