# Generated by Django 2.2.4 on 2019-08-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinCatalog', '0012_auto_20190830_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgcoin',
            old_name='coin',
            new_name='coin_id',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='mass',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='nominal',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='original_equipment',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='probe',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='pure_metal',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='thickness',
        ),
        migrations.AddField(
            model_name='coin',
            name='catalog_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
