# Generated by Django 2.2.4 on 2019-08-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinCatalog', '0013_auto_20190831_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='category',
        ),
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
