# Generated by Django 2.2.4 on 2019-08-30 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coinCatalog', '0014_auto_20190831_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('short_name', models.CharField(max_length=150, null=True)),
                ('nominal', models.CharField(max_length=150, null=True)),
                ('quality', models.CharField(max_length=50, null=True)),
                ('probe', models.CharField(max_length=50, null=True)),
                ('original_equipment', models.CharField(max_length=255, null=True)),
                ('pure_metal', models.CharField(max_length=255, null=True)),
                ('mass', models.CharField(max_length=50, null=True)),
                ('diameter', models.CharField(max_length=50, null=True)),
                ('thickness', models.CharField(max_length=50, null=True)),
                ('copies', models.CharField(max_length=50, null=True)),
                ('manufacturer', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinCatalog.Coin')),
            ],
        ),
    ]
