# Generated by Django 2.2.4 on 2019-08-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinCatalog', '0015_coindescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialoguser',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='dialoguser',
            name='photo_path',
        ),
        migrations.RemoveField(
            model_name='dialoguser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='dialoguser',
            name='state',
        ),
    ]
